#cloud-config
users:
  - name: root
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
package_upgrade: true
packages:
      - ca-certificates
      - curl
      - gnupg
      - vim
      - git
      - zip
      - unzip
      - openssl
      - libssl-dev
      - build-essential
      - libclang-dev
write_files:
  - path: /etc/prometheus.yml
    content: |
      global:
        scrape_interval: 1s
  
      scrape_configs:
      - job_name: "telemetry_metrics_prometheus"
        metrics_path: "/metrics"
        static_configs:
        - targets: ["10.0.1.3:3312"]
runcmd:
  - apt-get install pkg-config cmake clang lldb lld -y
  - apt-get install -y adduser libfontconfig1 musl
  - wget https://dl.grafana.com/enterprise/release/grafana-enterprise_10.2.1_amd64.deb
  - dpkg -i grafana-enterprise_10.2.1_amd64.deb
  - /bin/systemctl start grafana-server
  - wget https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz
  - tar -xvf prometheus-2.47.2.linux-amd64.tar.gz
  - cd prometheus-2.47.2.linux-amd64/ && rm prometheus.yml && mv /etc/prometheus.yml . && ./prometheus --config.file=prometheus.yml